print(50*"-","WELCOME TO GROCERY MANAGEMENT SYSTEM","-"*50)
vegetables={"Tomato": "₹30 per kg",
    "Potato": "₹25 per kg",
    "Onion": "₹40 per kg",
    "Carrot": "₹50 per kg",
    "Cabbage": "₹35 per kg",
    "Cauliflower": "₹45 per kg",
    "Spinach": "₹20 per kg",
    "Brinjal": "₹40 per kg",
    "Lady Finger": "₹60 per kg",
    "Capsicum": "₹70 per kg"}
fruits={"Apple": "₹180 per kg",
    "Banana": "₹60 per dozen",
    "Mango": "₹150 per kg",
    "Orange": "₹120 per kg",
    "Grapes": "₹90 per kg",
    "Pineapple": "₹80 per piece",
    "Papaya": "₹50 per kg",
    "Watermelon": "₹40 per kg",
    "Guava": "₹70 per kg",
    "Pomegranate": "₹200 per kg"}
grocery={"Rice": "₹70 per kg",
    "Wheat Flour": "₹55 per kg",
    "Sugar": "₹45 per kg",
    "Salt": "₹20 per kg",
    "Cooking Oil": "₹180 per litre",
    "Mustard Oil": "₹160 per litre",
    "Tea": "₹500 per kg",
    "Coffee": "₹600 per kg",
    "Milk": "₹60 per litre",
    "Butter": "₹600 per kg",
    "Paneer": "₹400 per kg",
    "Dal (Lentils)": "₹120 per kg",
    "Besan (Gram Flour)": "₹90 per kg",
    "Poha": "₹80 per kg",
    "Sooji (Semolina)": "₹70 per kg",
    "Maida": "₹60 per kg",
    "Detergent": "₹120 per kg",
    "Soap": "₹35 per bar",
    "Toothpaste": "₹60 per tube"}
sports_toys={"Football": "₹800",
    "Cricket Bat": "₹1200",
    "Cricket Ball": "₹200",
    "Badminton Racket": "₹700",
    "Shuttlecock Pack": "₹150",
    "Tennis Racket": "₹1500",
    "Tennis Ball (Pack of 3)": "₹350",
    "Skipping Rope": "₹200",
    "Basketball": "₹900",
    "Yoga Mat": "₹600",
    "Remote Control Car": "₹1200",
    "Lego Set": "₹2500",
    "Toy Train": "₹1000",
    "Doll": "₹500",
    "Teddy Bear": "₹700",
    "Puzzle Game": "₹300",
    "Building Blocks": "₹600",
    "Action Figure": "₹800",
    "Board Game (Ludo/Chess)": "₹400",
    "Toy Gun": "₹450"}
print(vegetables)
